@ProjectManagementSaaS.Api_HostAddress = http://localhost:5015

GET {{ProjectManagementSaaS.Api_HostAddress}}/health/live
Accept: application/json

###

GET {{ProjectManagementSaaS.Api_HostAddress}}/health/ready
Accept: application/json

###
