export const routePaths = {
  root: '/',
  signIn: '/auth/sign-in',
  app: '/app',
  unauthorized: '/app/access-denied',
  myTasks: '/app/my-tasks',
  calendar: '/app/calendar',
  notifications: '/app/notifications',
  profile: '/app/profile',
  tenants: '/app/tenants',
  subscriptions: '/app/subscriptions',
  organizations: '/app/organizations',
  departments: '/app/departments',
  teams: '/app/teams',
  users: '/app/users',
  roles: '/app/roles',
  permissions: '/app/permissions',
  clients: '/app/clients',
  projects: '/app/projects',
  projectDetails: (projectId: string) => `/app/projects/${projectId}`,
  projectMembers: (projectId: string) => `/app/projects/${projectId}/members`,
  projectSettings: (projectId: string) => `/app/projects/${projectId}/settings`,
  projectDashboard: (projectId: string) => `/app/projects/${projectId}/dashboard`,
  workItems: '/app/work-items',
  workItemDetails: (workItemId: string) => `/app/work-items/${workItemId}`
} as const;
